stage:
- build

build:
- maven:
  - mvn clean install -Dmaven.repo.local=/root/.m2/${JOB_NAME}
- docker:
  - cd docker && docker build . -t $image
  - docker images | grep cloudzcp
- docker.push:
    imageName: $image
    credentialsId: dockerhub

env:
  image: cloudzcp/zcp-iam:1.1.0-alpha

agent:
  profile: [maven, docker, kubectl]
  volumes:
  - pvc:zcp-jenkins-mvn-repo: /root/.m2
