stage:
#- Build
- Deploy

Build:
- maven:
  - mvn clean install -T 4 -Dmaven.repo.local=/root/.m2/${JOB_NAME}
- docker:
  - cd docker && docker build . -t $image
  - docker images | grep cloudzcp
- docker.push:
    imageName: $image
    credentialsId: dockerhub

Deploy:
- kubectl:
  - apk add bash
  - export keycloak_pwd=${keycloak_pwd//[\$\$]/\$}
  - env
  - cd $yaml && bash -x template.sh
  - kubectl apply -R -f $yaml/.tmp
  - kubectl scale deploy zcp-iam --replicas 1 -n $ns

env:
  image: cloudzcp/zcp-iam:1.1.0-alpha
  yaml: k8s/template
  ns: console

agent:
  profile: [maven, docker, kubectl]
  volumes:
  - pvc:zcp-jenkins-mvn-repo: /root/.m2
