apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    cloudzcp.io/zcp-system-admin: "yes"
  name: zcp-system-admin2
  namespace: console
# TODO
imagePullSecrets:
- name: bluemix-cloudzcp-secret

# TODO
# should add the imagePullSecrets into the default sa of the zcp-system namespace
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    cloudzcp.io/zcp-system-admin: "yes"
  name: zcp-system-admin2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: zcp-system-admin2
  namespace: console