nameOverride: 'mongo'

mongodbDatabase: iam
mongodbUsername: iam
mongodbPassword: iam!23$

#image:
#  registry: registry.au-syd.bluemix.net
#  repository: /cloudzcp/mongodb
#  tag: 3.4.9-r1

persistence:
  enabled: true
  existingClaim: zcp-iam-mongodb

tolerations:
  - effect: NoSchedule
    key: management
    operator: Equal
    value: "true"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/arch
          operator: In
          values:
          - amd64
        - key: role
          operator: In
          values:
          - management
